#!/bin/sh
# Bspwm autostart script
# Author: yaelooo

# Set paths
bsp="$HOME/.config/bspwm"
scr="$bsp/scripts"

# Run Sxhkd
pgrep -x sxhkd >/dev/null || sxhkd -c "$bsp"/sxhkdrc &
# Run Picom
pgrep -x picom >/dev/null || picom --config $bsp/picom/picom.conf &
# Run Xsettingsd
pgrep -x xsettingsd >/dev/null || xsettingsd --config="$bsp"/xsettingsd &
# Run polkit agent
pgrep -x xfce-polkit >/dev/null || /usr/lib/xfce-polkit/xfce-polkit &
# Run Greenclip
pgrep -x greenclip >/dev/null || greenclip daemon &
# Run Dropbox
pgrep -x dropbox >/dev/null || dropbox daemon &
# Run Mpd
# pgrep -x mpd >/dev/null || exec mpd &

# Set wallpaper lightdm
sh "$scr"/lightdm
# Set polybar
sh "$scr"/polybar
# Set dunst
sh "$scr"/dunst

# Set wallpaper with wal
wal -i ~/Pictures/wallpapers/
# Import colors from wal
. "${HOME}/.cache/wal/colors.sh"

# Set bspwm workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Manage all the unmanaged windows.
bspc wm --adopt-orphans

# Set colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color5"

# Set bspwm config
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

# Set window gaps
bspc config border_width 2
bspc config window_gap 7
bspc config split_ratio 0.52

# Set window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a kitty state=floating rectangle=855x498+255+135
bspc rule -a kitty state=floating center=true
# bspc rule -a pcmanfm state=floating rectangle=855x498+255+135
bspc rule -a pcmanfm state=floating center=true
bspc rule -a tidal-hifi state=floating sticky=on locked=on
