#!/usr/bin/env bash

# Import Current Theme
RASI="/home/yaelo/.config/rofi/config.rasi"

# Theme Elements
prompt="$(hostname) ($(echo $DESKTOP_SESSION))"
mesg="Uptime : $(uptime -p | sed -e 's/up //g')"

# Options
layout=$(cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2)
option_1=" Shutdown"
option_2=" Reboot"
option_3=" Logout"
option_4=" Suspend"

cnflayout=$(cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2)
yes=' Yes'
no=' No'

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4" | rofi_cmd
}

# Confirmation CMD
confirm_cmd() {
	rofi -dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?' \
		-theme ${RASI}
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Confirm and execute
confirm_run() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		${1} && ${2} && ${3}
	else
		exit
	fi
}

# Execute Command systemctl hibernate
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		confirm_run systemctl poweroff
	elif [[ "$1" == '--opt2' ]]; then
		confirm_run systemctl reboot
	elif [[ "$1" == '--opt3' ]]; then
		confirm_run bspc quit
	elif [[ "$1" == '--opt4' ]]; then
		confirm_run systemctl suspend
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$option_1)
	run_cmd --opt1
	;;
$option_2)
	run_cmd --opt2
	;;
$option_3)
	run_cmd --opt3
	;;
$option_4)
	run_cmd --opt4
	;;
esac
